### ISSUE TITLE
fast_float: RGB->Lab wrong float conversion

### ISSUE THREAD

**Issue by mahupl** [mm2/Little-CMS#325]
I am converting the float RGB data {1, 0, 0} from sRGB to Lab. I am using version 2.13.1.
With fast_plugin I get:
[0]	float	0.542900741
[1]	float	0.818905949
[2]	float	0.776058614

Without fast_plugin I get:
[0]	float	54.2900734
[1]	float	80.8210144
[2]	float	69.8949432

Aside from a factor of 100, a and b are quite different. My code:
```
cmsUInt32Number	srcFormat;
cmsUInt32Number	destFormat;
cmsHTRANSFORM	transformHandle;
	
srcFormat = cmsFormatterForColorspaceOfProfile(srcProfileHandle, 4, true);
destFormat = cmsFormatterForColorspaceOfProfile(destProfileHandle, 4, true);

transformHandle = cmsCreateTransform(srcProfileHandle, srcFormat, destProfileHandle, destFormat, INTENT_PERCEPTUAL, 0);
if (transformHandle)
{
  float srcBuffer[3] = {1, 0, 0};
  float destBuffer[3];
  cmsDoTransform(transformHandle, srcBuffer, destBuffer, 1);
  cmsDeleteTransform(transformHandle);
}

```

I just checked with float RGB->CMYK and it behaves the same way.
With fast_plugin I get:
[0]	float	0.00546272984
[1]	float	0.965560376
[2]	float	0.924757778
[3]	float	0.00595101854

Without fast_plugin I get:
[0]	float	0.546272993
[1]	float	96.5560379
[2]	float	92.4757766
[3]	float	0.595101833

Here the values just differ by a factor of 100. Apart from that, they are the same.

**Comment by mm2** [comment]
Right, the optimizer picks this case as suitable whilst is really not.
Fixed in a9796f61c682f5320ff572c888062ee34315b836 thanks for reporting

**Comment by mahupl** [comment]
The Lab case works now. Thank you.

But the CMYK problem is still there. You maybe missed that because I added it later.

**Comment by mm2** [comment]
> But the CMYK problem is still there. You maybe missed that because I added it later.


Fixed in 89c9d176b4349367ecd45f85b94aea3bf6f372c9

**Comment by mahupl** [comment]
Yes, thanks again.
