### ISSUE TITLE
Gnome 43 Apparently Crashes because of a lcms2 Crash

### ISSUE THREAD

**Issue by SuperJC710e** [mm2/Little-CMS#349]
Hi, first of all, thanks for your projects! :+1: 

I'm posting this to see if you think this is the case as well. Here's the bug report I filed with Gnome. [https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6162](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6162). They concluded that the cause is a bug in `lcms2`. It looks like, according to the link to the issue, ( #344 )  they reference, that the bug has been fixed, however, it appears it will not be fixed in downstream until a version bump, or similar.

**Comment by mm2** [comment]
Thanks.
Not sure if is the case. The crash is due to closing an icc profile. May be related.
For now, you can update colord https://github.com/hughsie/colord/pull/146 
If you think this is a killer bug and lcms can solve it, I could create a 2.14.1 to fix that, just let me know.

**Comment by SuperJC710e** [comment]
Thanks @mm2 ! I took a look at `colord`. I tried to build the latest myself and install some pieces, but that didn't work. Not really too sure how to build `meson` stuff, or how to make a locally updated fedora package from latest git, or I would tackle it. I'll see if I can learn more, but like everyone, time is limited...

**Comment by ValZapod** [comment]
>If you think this is a killer bug and lcms can solve it, I could create a 2.14.1 to fix that, just let me know.

It makes using thunderbolt 3 displays impossible, I suppose, what do you mean create? You mean tag? It is fixed in master?

**Comment by SuperJC710e** [comment]
> > If you think this is a killer bug and lcms can solve it, I could create a 2.14.1 to fix that, just let me know.
> 
> It makes using thunderbolt 3 displays impossible, I suppose since they have primaries and white point in EDID, what do you mean create? You mean tag? It is fixed in master?

I did end up using `mock` to build "updated" packages from the latest git. It didn't fix the issue for me though. I think there's more at play...

It is quite aggravating to not be able to use my laptop plugged into my TB dock with the external monitor. I either have to use Windows (ugh...), or a distro locked at Gnome 42 (also ugh...). Every distro I've tried that is at Gnome 43 crashes in the same or similar way...I see you found my issue over on the Gnome gitlab for gnome-shell too: [6162](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6162). I thought I was alone in experiencing the issue, but at least there's 2 of us now...

Hope it get's fixed soon! 👍

**Comment by ValZapod** [comment]
>either have to use Windows (ugh...)

Hard to use HDR on linux, so not ugh... I use linux only in Vmware. and now in Windows's WSLv1.

**Comment by mm2** [comment]
Hi,

>It makes using thunderbolt 3 displays impossible, I suppose, what do you mean create? You mean tag? It is fixed in master?

It was fixed on master 2 days after getting the bug reported. That was November-2022

 

fix memory corruption when unregistering plugins · ***@***.*** (github.com) <https://github.com/mm2/Little-CMS/commit/a9e4601ceb3a185d4f78cc0cfbd285cf0c399e9d> 

 

AFAIK, colord which is the other involved package, has already fixed this bug on their side.

 

For “create” I mean make a formal release, which involves tagging in github but also running all qualification tests on different supported platforms, changing version number in source code and sending a mail to the mailing list with the announcement.

 

Regards

Marti Maria

The LittleCMS Project

 <https://www.littlecms.com> https://www.littlecms.com

**Comment by thomas-weber** [comment]
Please check that this is not due to an interaction between _mutter_ and _colord_: https://gitlab.gnome.org/GNOME/mutter/-/issues/2659. The problem has since been fixed in _mutter_. Unless new information appears, I would suggest to close this issue for lcms2.

**Comment by mm2** [comment]
Fixed in 2.15 and in other packages like mutter
